github:
  is_project_page: false
theme: jekyll-theme-cayman
title: Welcome to Ali Safa's Research Portfolio on Ethical AI
description: Signal Processing and Embedded Machine Learning for Ultra Safe Robotics
author: Ali Safa

header_pages:
  - index.md
  - about.md
